[cosmic-ray]
module-path = "src/des/application/boundary_rules_generator.py"
timeout = 10.0
excluded-modules = []
test-command = "pytest -x tests/des/unit/test_boundary_rules_generator.py"

[cosmic-ray.distributor]
name = "local"

[cosmic-ray.execution-engine]
name = "local"
