[cosmic-ray]
module-path = "src/des/application/validator.py"
timeout = 10.0
excluded-modules = []
test-command = "pytest -x tests/des/"

[cosmic-ray.distributor]
name = "local"

[cosmic-ray.execution-engine]
name = "local"
